stages:
  - build
  - test
  - deploy
  - dast

include:
  - template: Security/DAST.gitlab-ci.yml

build_job:
  stage: build
  script:
    - echo "Building app..."

test_job:
  stage: test
  script:
    - echo "Running tests..."

deploy_job:
  stage: deploy
  script:
    - echo "Deploying app..."

dast:
  stage: dast
  variables:
    DAST_TARGET_URL: "https://dev-app.example.com"
    DAST_FULL_SCAN_ENABLED: "true"

    
    DAST_AUTH_URL: "https://dev-app.example.com/login"
    # DAST_AUTH_USERNAME: "ofCicdPlatformGitLabProd-fdas-infobank@okta.service.account"
    # DAST_AUTH_PASSWORD: "IB$2025%InSol.SA"
    DAST_AUTH_USERNAME: "$DAST_USERNAME"      
    DAST_AUTH_PASSWORD: "$DAST_PASSWORD"       
    DAST_AUTH_USERNAME_FIELD: "css:input[id=email]"
    DAST_AUTH_PASSWORD_FIELD: "css:input[id=password]"
    DAST_AUTH_SUBMIT_FIELD: "css:button[id=loginButton]"
    DAST_AUTH_REPORT: "true"
    DAST_CRAWL_GRAPH: "true"

  artifacts:
    reports:
      dast: gl-dast-report.json
    paths:
      - gl-dast-report.json
      - gl-dast-debug.log
      - gl-dast-crawl.svg
    expire_in: 2 weeks

  
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
      when: manual
