stages:
  - build
  - test
  - deploy
  - dast

include:
  - template: Security/DAST.gitlab-ci.yml

build_job:
  stage: build
  script:
    - echo "Building app..."

test_job:
  stage: test
  script:
    - echo "Running tests..."

deploy_job:
  stage: deploy
  script:
    - echo "Deploying app..."

dast:
  stage: dast
  variables:
    # ===== OKTA LOGIN PAGE =====
      DAST_AUTH_URL: "https://company.okta.com/app/amazon_aws/exk123abc/sso/saml"

      # ===== OKTA CREDENTIALS =====
      DAST_AUTH_USERNAME: "your-okta-user@company.com"
      DAST_AUTH_PASSWORD: "your-okta-password"

      # ===== OKTA FORM FIELD SELECTORS (Okta's HTML) =====
      DAST_AUTH_USERNAME_FIELD: "css:input[id=okta-signin-username]"
      DAST_AUTH_PASSWORD_FIELD: "css:input[id=okta-signin-password]"
      DAST_AUTH_FIRST_SUBMIT_FIELD: "css:button[id=okta-signin-submit]"
      DAST_AUTH_SUBMIT_FIELD: "css:button[id=okta-signin-submit]"

      # ===== YOUR WEBSITE (Only change the domain) =====
      DAST_TARGET_URL: "https://your-website.com/dashboard"
      DAST_AUTH_REPORT: "true"
      DAST_CRAWL_GRAPH: "true"
      DAST_FULL_SCAN: "true"
  artifacts:
    reports:
      dast: gl-dast-report.json
    paths:
      - gl-dast-report.json
      - gl-dast-debug.log
      - gl-dast-crawl.svg
    expire_in: 2 weeks

  
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
      when: manual
